name: GitHub Action
run-name: ${{github.actor}} is build digit data
on: [push]
jobs:
  Build-Digit-Data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [lts/*]
    steps:
      - name: Check Out Repository code
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          vision: 9

      - name: Checkout Node.js ${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          user-email:
          create-target-branch-if-needed: true
          source-directory: "dist"
          destination-github-username: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
          destination-repository-name: ${{ secrets.DEPLOY_GITHUB_REPOSITORY }}
